nerd4ever_kaya_pabx:
  storage:
    dir: "%env(STORAGE_DIR)%"
  persistence:
    doctrine:
      entity_manager: default
      table_prefix: ~
      enable: true
  security:
    library: "%env(SECURITY_LAYER_LIBRARY)%"
  tenancy:
    # Defina uma classe de tenancy personalizada. Essa classe deve estender Nerd4ever\Kaya\PabxBundle\Model\AbstractTenancy.
    # Se nenhuma classe de tenancy personalizada for definida, a classe padrão utilizada será Nerd4ever\Kaya\PabxBundle\Entity\Tenancy
    # Certifique-se de que a classe de tenancy personalizada tenha um repositório implementando Nerd4ever\Kaya\PabxBundle\Repository\TenancyRepositoryInterface.
    classname: ~